generate_report:
  fields:
    config_entry_id:
      selector:
        config_entry:
          integration: ere_report
    year:
      selector:
        number:
          min: 2000
          max: 2100
          mode: box
    quarter:
      selector:
        select:
          options:
            - "1"
            - "2"
            - "3"
            - "4"
